"""Skill(s): new_skill. Generated by `make skill-generic` -- edit freely."""

from robot_agent.skills import log_data

def new_skill(node, **params) -> dict:
    """Skill `new_skill`. TODO: replace this stub."""
    log_data({'msg': f'new_skill called with params={params}'})
    return {'isdone': True, 'msg': 'new_skill stub'}
