"""Skill(s): rest_detect. Generated by `make skill-detect` -- edit freely.

This file follows the "detect" pattern:
  - _fetch_data_<skill> pulls a frame from a registered camera agent.
  - the skill body sends that frame to a TCP detector client and logs the result.
"""

from robot_agent.skills import log_data
from robot_agent.state import current

def _fetch_data_rest_detect(node):
    """Mock image fetch. Replace 'head_rgb'/'head_depth' with the agent
    names you registered in the Connections panel."""
    a = node.agents
    rgb         = a['head_rgb'].get()         if 'head_rgb'         in a else None
    depth       = a['head_depth'].get()       if 'head_depth'       in a else None
    cam_params  = a['head_cam_params'].get()  if 'head_cam_params'  in a else None
    if rgb is None:
        raise Exception("camera agent 'head_rgb' not registered — add it in the Connections panel")
    return {
        'rgb':        rgb.get('im')         if isinstance(rgb,        dict) else rgb,
        'depth':      depth.get('im')       if isinstance(depth,      dict) else depth,
        'cam_params': cam_params.get('cam_params') if isinstance(cam_params, dict) else cam_params,
    }


def rest_detect(node, **params) -> dict:
    """Skill `rest_detect` — mock detector flow.

    1. Fetch an image from the camera agent (see _fetch_data_rest_detect).
    2. Send the image + params to the detector client over TCP.
    3. Log the result and return it.

    Edit the agent name, detector key, and request payload to match your setup.
    """
    log_data({'msg': f'rest_detect called with params={params}'})

    inp = params.pop('inputs', 'object')

    # 1. fetch image
    data = _fetch_data_rest_detect(node)

    # 2. call the detector client (TCP). Register a TCP client named 'detector'
    #    (or rename below) in the Connections panel.
    detector = current().dm.get_client('inferix')
    if detector is None:
        raise Exception("TCP client 'detector' not registered — add it in the Connections panel")



    result = detector.infer_array(data['rgb'], conf=0.3, iou=0.7, prompt=inp)


    # 3. log the annotated image so it shows up in the UI Camera panel
    log_data({'log_image': data['rgb']})

    return {'isdone': True, 'msg': f'rest_detect done', 'result': result}
