# Maps skill_name → (module_path, func_name)
# Module paths point to kcare_robot/skills/

_PKG = 'kcare_robot.skills'

SKILL_CONFIGS: dict[str, tuple[str, str]] = {
    'detect':           (f'{_PKG}.recognition', 'find'),
    'find':             (f'{_PKG}.recognition', 'find'),
    'find_arm':         (f'{_PKG}.recognition', 'find_arm'),
    'grasp_succeed':    (f'{_PKG}.recognition', 'grasp_succeed'),
    'pick':             (f'{_PKG}.pick',        'pick'),
    'pick_card':        (f'{_PKG}.pick',        'pick_card'),
    'fine_move':        (f'{_PKG}.pick',        'fine_move'),
    'open_drawer':      (f'{_PKG}.pick',        'open_drawer'),
    'close_drawer':     (f'{_PKG}.pick',        'close_drawer'),
    'stack':            (f'{_PKG}.pick',        'stack'),
    'approach':         (f'{_PKG}.approach',    'approach_close'),
    'approach_close':   (f'{_PKG}.approach',    'approach_close'),
    'approach_closef':  (f'{_PKG}.approach',    'approach_closef'),
    'placeat':          (f'{_PKG}.approach',    'placeat'),
    'placep':           (f'{_PKG}.approach',    'placep'),
    'arm_joints':       (f'{_PKG}.arm',         'arm_joints'),
    'arm_pose':         (f'{_PKG}.arm',         'arm_pose'),
    'movel':            (f'{_PKG}.arm',         'movel'),
    'movej':            (f'{_PKG}.arm',         'movej'),
    'movet':            (f'{_PKG}.arm',         'movet'),
    'movelf':           (f'{_PKG}.arm',         'movelf'),
    'place':            (f'{_PKG}.place',       'place'),
    'collect_card':     (f'{_PKG}.place',       'collect_card'),
    'return_card':      (f'{_PKG}.place',       'return_card'),
    'wipe':             (f'{_PKG}.place',       'wipe'),
    'init_arm':         (f'{_PKG}.goto_ready',  'init_arm'),
    # 'enable':           (f'{_PKG}.goto_ready',  'enable'),
    'lift':             (f'{_PKG}.lift',        'lift'),
    'lift_state':       (f'{_PKG}.lift',        'lift_state'),
    'dlift':            (f'{_PKG}.lift',        'dlift'),
    'mobile_pose':      (f'{_PKG}.mobile',      'mobile_pose'),
    'move':             (f'{_PKG}.mobile',      'move'),
    'moveb':            (f'{_PKG}.mobile',      'moveb'),
    'forward':          (f'{_PKG}.mobile',      'forward'),
    'turn':             (f'{_PKG}.mobile',      'turn'),
    'rotate':           (f'{_PKG}.mobile',      'rotate'),
    'head_state':       (f'{_PKG}.head',        'head_state'),
    'moveh':            (f'{_PKG}.head',        'moveh'),
    'grip':             (f'{_PKG}.grip',        'grip'),
    'inform':           (f'{_PKG}.inform',      'inform'),
    'select_response':  (f'{_PKG}.select',      'select_response'),
    'get3d':            (f'{_PKG}.pointcloud',  'get3d'),
    'llm':              (f'{_PKG}.vlm',         'llm'),
}
